### ISSUE TITLE
Card image overflow

### ISSUE THREAD

**Issue by danj3000** [donovanamitchell/ashes-reborn-deck-builder#18]
When I click to view a card, it looks like this...
![Screenshot_20210923-181424_AshesRebornDeckBuilder](https://user-images.githubusercontent.com/32267086/134553710-2b4b9d6b-77f1-4743-a084-506dccd979a5.jpg)

**Comment by donovanamitchell** [comment]
I thought I had this fixed, but apparently regressed when I fixed a different, worse graphical bug. Should be an easy fix.
